install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("descr")
install.packages('leaflet')
install.packages('DescTools')
install.packages('lsr')
install.packages('pwr')
install.packages('effsize')
install.packages('ggpubr')
install.packages('broom')
install.packages('rcompanion')
install.packages('tidyr')
install.packages("gridExtra")
install.packages("rsq")
install.packages("afex")
install.packages("ggcorrplot") ## make pretty corrplot
install.packages("GGally") ## scatterplot matrix function
install.packages("gtrendsR")
install.packages("olsrr") ## ols diagnostics
install.packages("flextable")
install.packages("stargazer")
install.packages("sjPlot")
install.packages("webshot")
#webshot::install_phantomjs()
#install.packages("magick")
install.packages("scales")
install.packages("Hmisc")

